# Generated by Django 5.1.5 on 2025-01-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=30)),
                ('blue', models.IntegerField(default=0)),
                ('red', models.IntegerField(default=0)),
                ('yellow', models.IntegerField(default=0)),
                ('green', models.IntegerField(default=0)),
                ('white', models.IntegerField(default=0)),
            ],
        ),
    ]
