# Generated by Django 5.1.5 on 2025-01-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='username',
            old_name='spot',
            new_name='overall_spot',
        ),
    ]
